### ISSUE TITLE
api 받아와 카드뷰 뿌리는 작업

### ISSUE THREAD

**Issue by EdenKangdw** [love5757/sideJobCommunity#17]
api 내용 받아와서 카드뷰에 뿌리는 작업과 카드뷰 배치 작업입니다.

**Comment by love5757** [comment]
@EdenKangdw 
API 받아 와서 카드뷰 뿌리는 작업이 완료인가요?  기본적인게 완성 되서 Merged 되었으면..  수정이나 고도화를 하시고 계시면 이슈 새로 등록해서 ~  TODO 만드시고 ~작업하시면 좋을꺼 같아요 ~

**Comment by EdenKangdw** [comment]
일단 api 받아서 기본 뷰 뿌리는 작업은 완료입니다. 뷰 수정등은 새로 이슈 만들어서 진행하겠습니다.
