### ISSUE TITLE
개발 서버 세팅

### ISSUE THREAD

**Issue by love5757** [love5757/sideJobCommunity#2]
- 리눅스 서버 셋팅 하나만 해주세요. PC에 무리가 갈것 같으면 이야기 하시면 제가 가지고 헤놀로지에 그냥 웹서버 구성 하도록 할께요
 - Centos 7

**Comment by soorokim** [comment]
[개발 서버 정보]
OS: CentOS7(1810)( G4560 베이스 가상운영체제, Ram 2G, SSD 40G )
디렉토리별 용량
---------------------------------
/home	25GB
/	10.5GB
/boot	500MB
swap	4GB
---------------------------------

[SSH] - 아래 글을 참고하여 설치
https://blog.inidog.com/p/201808031462

접속 주소 : soorokim.duckdns.org
포트 : 19220 (프로젝트 회의 시작날짜! 2월 20일ㅋㅋㅋ)
ID : user
PW : Javascript
su PW :  Javascript

[DB] - 아래 주소를 참고해서 설치함
https://zetawiki.com/wiki/CentOS7_MariaDB_%EC%84%A4%EC%B9%98
ID : root
PW: Javascript
